version: '3.8'
services:
  db:
    image: mariadb:$DB_MARIADB_VERSION
    container_name: $APP_CONTAINER_NAME-mysql
    restart: always
    ports:
      - $DB_MARIADB_PORT:3306
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_MARIADB_PASSWORD  # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - $VOLUMES_PATH_PREFIX/mysql_data:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.

  memcached:
    image: memcached:$DB_MEMCACHED_VERSION
    container_name: $APP_CONTAINER_NAME-memcached
    restart: always
    entrypoint: memcached -m 256
          
  seafile:
    image: seafileltd/seafile-mc:$APP_VERSION
    container_name: $APP_CONTAINER_NAME
    restart: always
    ports:
      - "$APP_PORT:80"
#     - "443:443"  # If https is enabled, cancel the comment.
    volumes:
      - $VOLUMES_PATH_PREFIX/seafile_data:/shared   # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=$DB_MARIADB_HOST
      - DB_ROOT_PASSWD=$DB_MARIADB_PASSWORD  # Requested, the value shuold be root's password of MySQL service.
      - TIME_ZONE=$APP_TIME_ZONE  # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - SEAFILE_ADMIN_EMAIL=$APP_USER # Specifies Seafile admin user, default is 'me@example.com'.
      - SEAFILE_ADMIN_PASSWORD=$APP_PASSWORD     
      - SEAFILE_SERVER_LETSENCRYPT=false   # Whether to use https or not.
      - SEAFILE_SERVER_HOSTNAME=$DOMAIN # Specifies your host name if https is enabled.
    depends_on:
      - db
      - memcached
      
networks:
  default:
      name: "$APP_NETWORK"